spring:
  config:
    activate:
      on-profile: dev # dev 프로파일이 활성화 되어있을 때만 사용 가능
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true #
          timeout: 5000
          starttls:
            enable: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/back-end
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
webpush:
  subject: "${webpush.subject}"
  vapid:
    public-key: "${webpush.vapid.public-key}"
    private-key: "${webpush.vapid.private-key}"

