# 공통 설정 파일
# 개발환경 설정 파일은 application-dev.yml
# 운영환경 설정 파일은 application-prod.yml

spring.application.name: back-end
spring:
  profiles:
    default: dev
  mail:
    host: ${mail.host}
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true #
          timeout: 5000
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger # swagger-ui 접근 경로. 해당 경로로 접근 시 /swagger/index.html로 리다이렉션 됨


cors:
  allowed-origins: "http://localhost:3000"
server:
  servlet:
    session:
      cookie:
        max-age: 2147483647


webpush:
  subject: "${webpush.subject}"
  vapid:
    public-key: "${webpush.vapid.public-key}"
    private-key: "${webpush.vapid.private-key}"