spring:
  config:
    activate:
      on-profile: dev # dev 프로파일이 활성화 되어있을 때만 사용 가능

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/back-end
    username: sa
    password:


